name: "기능 요청"
description: "기능 추가 또는 기능 개선에 대해서 제안이 있습니다!"
labels: ["request"]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "요약"
      description: "원하는 요청사항을 3줄 이내로 요약해주세요."

  - type: textarea
    validations:
      required: true
    attributes:
      label: "설명"
      description: "원하는 요청사항을 최대한 자세히 서술해주세요."
