name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-northeast-2'

      - name: Setup Node.js 16.19.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.19.0'
          cache: 'yarn'

      - name: Create .env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          envkey_DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          envkey_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

      - name: Install Dependencies
        run: yarn

      - name: Execute
        run: yarn deploy

      - name: 배포 성공 알림
        if: ${{ success() }}
        run: |
          curl -X POST -H "Content-type: application/json" \
          --data '{"content": null, "embeds": [{"description": "tech-news 배포 완료", "color": 65321}], "attachments": []}' \
          ${{ secrets.DISCORD_DEPLOYMENT_NOTIFICATION_WEBHOOK }}

      - name: 배포 실패 알림
        if: ${{ failure() }}
        run: |
          curl -X POST -H "Content-type: application/json" \
          --data '{"content": null, "embeds": [{"description": "tech-news 배포 실패", "color": 16711680}], "attachments": []}' \
          ${{ secrets.DISCORD_DEPLOYMENT_NOTIFICATION_WEBHOOK }}
